#! /bin/sh




file=60
file=$1

node=`echo "$file+2"|bc `
longflowsize=10
offerload=0


echo "-*-*-*-*-*-*-*-*-offerload=$offerload, node per rack=$node -*-*-*-*-*-*-*-*-*-*"

echo "tcp";date
#./waf --run "scratch/Burstiness --NumberofRacks=1 --NumberofApps=1 --Stop=1 --UseLongFlows=1  --offerload=$offerload --ECNMode=0  --DCTCPMode=0 --RTCPMode=0 --ICTCPMode=0  --RDTCPMode=0  --rto_min=10 --MachinesPerRack=$node --longflowsize=$longflowsize " >dataset/burstiness/$file/tmp_tcp

echo "dctcp";date
#./waf --run "scratch/Burstiness --NumberofRacks=1 --NumberofApps=1 --Stop=1 --UseLongFlows=1  --offerload=$offerload --ECNMode=1  --DCTCPMode=1 --RTCPMode=0 --ICTCPMode=0  --RDTCPMode=0  --rto_min=10 --MachinesPerRack=$node  --longflowsize=$longflowsize " >dataset/burstiness/$file/tmp_dctcp

echo "rtcp";date
#./waf --run "scratch/Burstiness --NumberofRacks=1 --NumberofApps=1 --Stop=1 --UseLongFlows=1  --offerload=$offerload --ECNMode=0  --DCTCPMode=0 --RTCPMode=1 --ICTCPMode=0  --RDTCPMode=0  --rto_min=10 --MachinesPerRack=$node  --longflowsize=$longflowsize " >dataset/burstiness/$file/tmp_rtcp 

echo "rdtcp";date
./waf --run "scratch/Burstiness --NumberofRacks=1 --NumberofApps=1 --Stop=1 --UseLongFlows=1  --offerload=$offerload  --ECNMode=1  --DCTCPMode=0 --RTCPMode=1 --ICTCPMode=0  --RDTCPMode=1  --RDTCP_CONTROLLER_Mode=1 --rto_min=10 --MachinesPerRack=$node  --longflowsize=$longflowsize " >dataset/burstiness/$file/tmp_rdtcp

echo "ictcp";date
#./waf --run "scratch/Burstiness --NumberofRacks=1 --NumberofApps=1 --Stop=1 --UseLongFlows=1  --offerload=$offerload  --ECNMode=0  --DCTCPMode=0 --RTCPMode=1 --ICTCPMode=1  --RDTCPMode=0  --rto_min=10 --MachinesPerRack=$node  --longflowsize=$longflowsize " >dataset/burstiness/$file/tmp_ictcp

date
