#! /bin/sh


file=50
node=51


file=$1
node=`echo "$file+1"|bc `

echo "file=$file, node=$node"

#./waf --run "scratch/FCT --NumberofRacks=1 --NumberofApps=1 --Stop=10 --UseLongFlows=0  --Use_RED_Mode=0  --ECNMode=0  --DCTCPMode=0 --RTCPMode=0 --ICTCPMode=0  --RDTCPMode=0  --rto_min=10 --MachinesPerRack=$node  " >dataset/fct/varying_num_of_nodes_fix_32kb/$file/tmp_tcp

#./waf --run "scratch/FCT --NumberofRacks=1 --NumberofApps=1 --Stop=10 --UseLongFlows=0  --Use_RED_Mode=0  --ECNMode=1  --DCTCPMode=1 --RTCPMode=0 --ICTCPMode=0  --RDTCPMode=0  --rto_min=10 --MachinesPerRack=$node  " >dataset/fct/varying_num_of_nodes_fix_32kb/$file/tmp_dctcp

#./waf --run "scratch/FCT --NumberofRacks=1 --NumberofApps=1 --Stop=10 --UseLongFlows=0  --Use_RED_Mode=0  --ECNMode=0  --DCTCPMode=0 --RTCPMode=1 --ICTCPMode=0  --RDTCPMode=0  --rto_min=10 --MachinesPerRack=$node  " >dataset/fct/varying_num_of_nodes_fix_32kb/$file/tmp_rtcp 

./waf --run "scratch/FCT --NumberofRacks=1 --NumberofApps=1 --Stop=10 --UseLongFlows=0  --Use_RED_Mode=0  --ECNMode=1  --DCTCPMode=0 --RTCPMode=1 --ICTCPMode=0  --RDTCPMode=1  --RDTCP_CONTROLLER_Mode=1 --rto_min=10 --MachinesPerRack=$node  " >dataset/fct/varying_num_of_nodes_fix_32kb/$file/tmp_rdtcp

#./waf --run "scratch/FCT --NumberofRacks=1 --NumberofApps=1 --Stop=10 --UseLongFlows=0  --Use_RED_Mode=0  --ECNMode=0  --DCTCPMode=0 --RTCPMode=1 --ICTCPMode=1  --RDTCPMode=0  --rto_min=10 --MachinesPerRack=$node  " >dataset/fct/varying_num_of_nodes_fix_32kb/$file/tmp_ictcp

